import {
  profile,
  user1,
  user2,
  user3,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
} from "../../assets/images";
import user10 from "../../assets/images/user10.jpg";


export const userData = [
  {
    id: 1,
    name: "Peggie",
    age: 28,
    hobbies: ["Concerts", "Festivals", "Photography"],
    bio: "Hey there! My name is Peggie. I'm a passionate fashion photographer with a love for capturing the beauty in everyday life. When I'm not behind the lens, you'll find me immersing myself in the energy of live music at concerts and festivals. Exploring new cultures and cuisines is my idea of a perfect adventure. Let's share stories over a cup of coffee and see where our shared passions take us!",
    distance: "3 miles away",
    imgPath: user10,
  },
  {
    id: 2,
    name: "Diana",
    age: 30,
    hobbies: ["Hiking", "Cooking", "Music"],
    bio: "Hi there! I'm Diana, a nature lover who finds joy in the kitchen and the magic of music. Let's go on a hike and then cook up a storm together. Seeking someone to share adventures and good food with.",
    distance: "10 miles away",
    imgPath: user2,
  },
  {
    id: 3,
    name: "Sophie",
    age: 26,
    hobbies: ["Painting", "Yoga", "Traveling"],
    bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar. Let's embark on a journey of self-discovery together, exploring the world and creating masterpieces along the way.",
    distance: "2 miles away",
    imgPath: user3,
  },
  {
    id: 4,
    name: "Betty",
    age: 32,
    hobbies: ["Soccer", "Cooking", "Movies"],
    bio: "Hi there! I'm Betty, a soccer lover who finds joy in the kitchen and the magic of movies. Let's kick a ball around and then cook up a storm together. Seeking someone to share adventures and good food with.",
    distance: "5 miles away",
    imgPath: user4,
  },
  {
    id: 5,
    name: "Lily",
    age: 29,
    hobbies: ["Dancing", "Reading", "Hiking"],
    bio: "Hola! I'm Lily, a dance lover who finds joy in the rhythm of life. Books are my escape, and hiking fuels my spirit. Let's dance under the stars and get lost in stories over a cup of coffee. Eager to meet someone to share life's dance with.",
    distance: "7 miles away",
    imgPath: user5,
  },
  {
    id: 6,
    name: "Chiara",
    age: 28,
    hobbies: ["Singing", "Writing", "Sailing"],
    bio: "Ciao! I'm Chiara, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
    distance: "4 miles away",
    imgPath: user6,
  },
  {
    id: 7,
    name: "Emma",
    age: 27,
    hobbies: ["Singing", "Writing", "Sailing"],
    bio: "Hi there! I'm Emma, a melody-maker who finds solace in writing and the serenity of sailing. Let's harmonize our voices and create music together. A poetic soul searching for someone to sail through life's highs and lows.",
    distance: "4 miles away",
    imgPath: user7,
  },
  {
    id: 8,
    name: "Sarah",
    age: 29,
    hobbies: ["Surfing", "Gardening", "Painting"],
    bio: "Hi there! I'm Sarah, a surfer who finds joy in the garden and the magic of painting. Let's ride the waves and then paint up a storm together. Seeking someone to share adventures and good food with.",
    distance: "8 miles away",
    imgPath: user8,
  },
  {
    id: 9,
    name: "Olivia",
    age: 28,
    hobbies: ["Yoga", "Hiking", "Photography"],
    bio: "Hello, I'm Olivia, a yoga enthusiast who finds peace in the serenity of nature and expression through photography. Let's go on a hike and then strike a pose together. Looking for someone to share adventures and good food with.",
    distance: "9 miles away",
    imgPath: user9,
  },
];

export const chatData = [
  {
    id: 1,
    name: "AI Bot",
    imgUrl: user10,
    age: null,
    isOnline: true,
    lastMessage:
      "Your account balance is $5,230. Would you like help with something else?",
    date: "2023-10-15",
    timeSent: "5 mins",
    chat: [
      {
        sender: "me",
        message: "Hi, I need help checking my account balance.",
        timestamp: "10:00 AM",
      },
      {
        sender: "AI Bot",
        message: "Sure, let me check that for you.",
        timestamp: "10:05 AM",
      },
      {
        sender: "AI Bot",
        message: "Your account balance is $5,230. Would you like help with something else?",
        timestamp: "10:10 AM",
      },
      {
        sender: "me",
        message: "Thanks! That’s all for now.",
        timestamp: "10:15 AM",
      },
    ],
  },
  {
    id: 2,
    name: "General Support",
    imgUrl: user2,
    age: null,
    isOnline: false,
    lastMessage: "Sure, let me escalate this issue for you.",
    date: "2023-10-14",
    timeSent: "10 mins",
    chat: [
      {
        sender: "me",
        message: "Hi, I have an issue with a recent transaction.",
        timestamp: "11:00 AM",
      },
      {
        sender: "Human Support",
        message: "Can you provide the transaction ID?",
        timestamp: "11:05 AM",
      },
      {
        sender: "me",
        message: "Yes, it’s TX1234567890.",
        timestamp: "11:10 AM",
      },
      {
        sender: "Human Support",
        message: "Thank you. I’ll check that for you.",
        timestamp: "11:15 AM",
      },
      {
        sender: "Human Support",
        message: "It looks like there was an issue. I’m escalating this to the relevant team.",
        timestamp: "11:20 AM",
      },
      {
        sender: "me",
        message: "Great, thank you!",
        timestamp: "11:25 AM",
      },
    ],
  },
  {
    id: 3,
    name: "AI Bot",
    imgUrl: user1,
    age: null,
    isOnline: true,
    lastMessage: "Is there anything else I can assist you with?",
    date: "2023-10-11",
    timeSent: "25 mins",
    chat: [
      {
        sender: "me",
        message: "I need to update my contact information.",
        timestamp: "2:00 PM",
      },
      {
        sender: "AI Bot",
        message: "You can update your contact information by visiting the settings page.",
        timestamp: "2:05 PM",
      },
      {
        sender: "me",
        message: "I tried that, but it didn’t work.",
        timestamp: "2:10 PM",
      },
      {
        sender: "AI Bot",
        message: "I’ll escalate this to human support for you. They will assist you further.",
        timestamp: "2:15 PM",
      },
      {
        sender: "me",
        message: "Thanks, much appreciated!",
        timestamp: "2:20 PM",
      },
    ],
  },
  {
    id: 4,
    name: "Fraud Detection Team",
    imgUrl: user9,
    age: null,
    isOnline: true,
    lastMessage: "Thank you for reporting the issue. We will investigate it immediately.",
    date: "2023-10-10",
    timeSent: "30 mins",
    chat: [
      {
        sender: "me",
        message: "Hi, I think I noticed some fraudulent activity on my account.",
        timestamp: "3:00 PM",
      },
      {
        sender: "Fraud Detection Team",
        message: "Can you please provide the details of the suspicious transaction?",
        timestamp: "3:05 PM",
      },
      {
        sender: "me",
        message: "Yes, there’s a charge from a merchant I don’t recognize.",
        timestamp: "3:10 PM",
      },
      {
        sender: "Fraud Detection Team",
        message: "Thank you for reporting. We will freeze your card and start an investigation.",
        timestamp: "3:15 PM",
      },
    ],
  },
  {
    id: 5,
    name: "Loan Assistance",
    imgUrl: user5,
    age: null,
    isOnline: false,
    lastMessage: "I'll forward the request to the loan department now.",
    date: "2023-10-09",
    timeSent: "35 mins",
    chat: [
      {
        sender: "me",
        message: "I need help with applying for a personal loan.",
        timestamp: "4:00 PM",
      },
      {
        sender: "Loan Assistance",
        message: "I can guide you through the process. Have you filled out the application form?",
        timestamp: "4:05 PM",
      },
      {
        sender: "me",
        message: "Yes, I did. What’s the next step?",
        timestamp: "4:10 PM",
      },
      {
        sender: "Loan Assistance",
        message: "Your application will be reviewed within 3 business days. I’ll forward your request to the loan department.",
        timestamp: "4:15 PM",
      },
    ],
  },
  {
    id: 6,
    name: "AI Bot",
    imgUrl: user1,
    age: null,
    isOnline: true,
    lastMessage: "You have successfully reset your password.",
    date: "2023-10-07",
    timeSent: "45 mins",
    chat: [
      {
        sender: "me",
        message: "I need help resetting my password.",
        timestamp: "6:00 PM",
      },
      {
        sender: "AI Bot",
        message: "Sure, I can assist with that. Please provide your account number.",
        timestamp: "6:05 PM",
      },
      {
        sender: "me",
        message: "It’s 1234567890.",
        timestamp: "6:10 PM",
      },
      {
        sender: "AI Bot",
        message: "Your password has been reset. You can now log in with your new password.",
        timestamp: "6:15 PM",
      },
      {
        sender: "me",
        message: "Thank you! That was quick.",
        timestamp: "6:20 PM",
      },
    ],
  },
];


export const datesData = [
  {
    id: 1,
    imgUrl: user1,
    name: "Dianna",
    lastName: "Jones",
    age: 25,
    city: "New York",
    country: "USA",
  },
  {
    id: 2,
    imgUrl: user2,
    name: "Jane",
    lastName: "Smith",
    age: 28,
    city: "Los Angeles",
    country: "USA",
  },
  {
    id: 3,
    imgUrl: user3,
    name: "Chiara",
    lastName: "Doe",
    age: 26,
    city: "London",
    country: "UK",
  },
  {
    id: 4,
    imgUrl: user4,
    name: "Ella",
    lastName: "Williams",
    age: 29,
    city: "Sydney",
    country: "Australia",
  },
  {
    id: 5,
    imgUrl: user5,
    name: "Jullie",
    lastName: "Brown",
    age: 30,
    city: "Paris",
    country: "France",
  },
  {
    id: 6,
    imgUrl: user6,
    name: "Olivia",
    lastName: "Miller",
    age: 27,
    city: "Berlin",
    country: "Germany",
  },
  {
    id: 7,
    imgUrl: user7,
    name: "William",
    lastName: "Wilson",
    age: 31,
    city: "Toronto",
    country: "Canada",
  },
  {
    id: 8,
    imgUrl: user8,
    name: "Sophia",
    lastName: "Moore",
    age: 29,
    city: "Tokyo",
    country: "Japan",
  },
  {
    id: 9,
    imgUrl: user9,
    name: "Diana",
    lastName: "Taylor",
    age: 32,
    city: "Mumbai",
    country: "India",
  },
  {
    id: 10,
    imgUrl: user4,
    name: "Alex",
    lastName: "Anderson",
    age: 30,
    city: "Moscow",
    country: "Russia",
  },
];

export const profileData = [
  {
    name: "Jacob Jones",
    age: 30,
    imgUrl: profile,
    hobbies: ["Hiking", "Photography", "Cooking"],
    bio: "I'm an adventurous person who loves exploring new places, trying out different cuisines, capturing moments through photography, and spending time in nature. I enjoy hiking on weekends and experimenting with new recipes in the kitchen. Traveling and experiencing different cultures are some of my greatest passions, and I'm always looking for my next adventure.",
  },
];
